services:
  - type: web
    name: spotify-clone
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /api/songs
